### PR TITLE
Wiki clean up

### PR DESCRIPTION
**Pull request by joecharles33**
- Decoupled user guide from Readme doc

- added an optional step to add an admin user with full cluster admin privilege using htpasswd

### CODE REVIEW

**Comment by jflowers** [comment]
@joecharles33 are there changes to the install/deploy content? The diff cannot show them if you made them in the same commit that the content was pulled out to a new file. BTW I originally added the install/deploy content as a seperate file and @usrbinkat merged it into the README...

**Comment by joecharles33** [comment]
> @joecharles33 are there changes to the install/deploy content? The diff cannot show them if you made them in the same commit that the content was pulled out to a new file. BTW I originally added the install/deploy content as a seperate file and @usrbinkat merged it into the README...

**Comment by joecharles33** [comment]
@jflowers there are no changes to the install/deploy content. I only decouple the Readme from the user guide and also added in optional step to add an admin user using htpasswd post deployment.

**Review by usrbinkat — APPROVED** [review]
lgtm

**Pull request closed without merging**
